spring.application.name=productservice

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# JWT Configuration
app.jwt.secret=your-secret-key-here-change-in-production
app.jwt.expiration_in_ms=86400000
app.jwt.header_string=Authorization
app.jwt.token.prefix=Bearer 