version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: fastmart-auth-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auth
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - fastmart-network

  db:
    image: postgres:18
    container_name: fastmart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./auth-service/src/main/resources/pg_data:/var/lib/postgresql/data
    networks:
      - fastmart-network

networks:
  fastmart-network:
    driver: bridge
