spring.application.name=productservice

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# Actuator
management.endpoints.web.exposure.include=env, info, health
management.endpoint.health.show-details=always